## 0. Imports

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from rapidfuzz import process

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

## 1. Data Loading

In [43]:
file_path = "../data/raw/Observations 2012-2025.xlsx"
#retrieve the number of sheets
print("number of sheets:", pd.ExcelFile(file_path).sheet_names)

df_species = pd.read_excel(file_path, sheet_name='ESPECES', header=None, usecols=[2, 3, 4])
df_species.columns = ['french_name', 'scientific_name', 'status']
# df_species.isna().sum()
# status has a missing value
df_species.head()

df_gps = pd.read_excel(file_path, sheet_name='GPS-MILIEU', header=1, usecols=[2, 3, 4, 5, 6, 7])
df_gps.columns = ['transect', 'X', 'Y', 'habitat', 'transect_id', 'point_id']
# df_gps.isna().sum()
# 0 missing values
df_gps.head()

df_obs = pd.read_excel(file_path, sheet_name='NOM FRANÇAIS', skiprows=[0, 1], header=0)
df_obs.columns = [
        'observer',              # Observer name
        'dept_code',             # Department code  
        'transect',              # Transect name
        'date',                  # Date
        'visit_number',          # 1st, 2nd or 3rd visit
        'clouds',                # Cloud cover
        'rain',                  # Rain intensity
        'wind',                  # Wind strength
        'visibility',            # Visibility
        'point',                 # Point number
        'start_time',            # Start time
        'species',               # Species name
        
        # Contact distances
        'auditory_0_25m',       
        'visual_0_25m',        
        'auditory_25_50m',       
        'visual_25_50m',   
        'auditory_50_100m', 
        'visual_50_100m',     
        'auditory_100m_plus', 
        'visual_100m_plus',   
        
        # Flight
        'flight',
        
        # Totals (4 columns)
        'auditory_total',   
        'visual__no_flight_total',         
        'auditory_visual_no_flight_total',
        'auditory_visual_with_flight_total',
        
        #Notes
        'Notes'
]
df_obs['date'] = pd.to_datetime(df_obs['date'])
df_obs.head()

number of sheets: ['ESPECES', 'GPS-MILIEU', 'NOM FRANÇAIS']

,observer,dept_code,transect,date,visit_number,clouds,rain,wind,visibility,point,...,auditory_50_100m,visual_50_100m,auditory_100m_plus,visual_100m_plus,flight,auditory_total,visual__no_flight_total,auditory_visual_no_flight_total,auditory_visual_with_flight_total,Notes
0,BELFAN David,972.0,Fond l'Etang,2014-04-12,1,2,1.0,1.0,1.0,1,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1,1.0,NaN
1,BELFAN David,972.0,Fond l'Etang,2014-04-12,1,2,1.0,1.0,1.0,1,...,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1,1.0,NaN
2,BELFAN David,972.0,Fond l'Etang,2014-04-12,1,2,1.0,1.0,1.0,1,...,NaN,NaN,NaN,NaN,NaN,0.0,2.0,2,2.0,NaN
3,BELFAN David,972.0,Fond l'Etang,2014-04-12,1,2,1.0,1.0,1.0,1,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1,1.0,NaN
4,BELFAN David,972.0,Fond l'Etang,2014-04-12,1,2,1.0,1.0,1.0,1,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1,1.0,NaN

In [45]:
obs_transects = set(df_obs['transect'].unique())
gps_transects = set(df_gps['transect'].unique())
print(obs_transects - gps_transects)  # transects dans obs mais pas dans gps

{'Forêt La Philippe', 'Desmarinière', 'Tunnel Didier ', 'MORNE ACA', 'Forêt La Reculée', 'BORELIE', 'ANSE COULEUVRE', 'Fond Baron ', 'BLIN'}

In [ ]:
# Corriger les transects mal orthographiés dans df_obs


df_obs['transect'] = df_obs['transect'].str.strip().str.lower()
df_gps['transect'] = df_gps['transect'].str.strip().str.lower()

obs_transects = df_obs['transect'].unique()
gps_transects = df_gps['transect'].unique()

mapping = {}
for obs_name in obs_transects:
    match, score, _ = process.extractOne(obs_name, gps_transects)
    if score >= 90 and score < 100:  # 100 = exact, 90+ = correspondance probable
        mapping[obs_name] = match
        print(f"Correction: {obs_name} -> {match} (score={score})")

df_obs['transect'] = df_obs['transect'].replace(mapping)

missing_after = set(df_obs['transect'].unique()) - set(df_gps['transect'].unique())
if missing_after:
    print("Transects encore manquants :", missing_after)
else:
    print("Tous les transects correspondent maintenant à df_gps !")

Correction: desmarinière -> desmarinières (score=96.0)
Tous les transects correspondent maintenant à df_gps !

In [47]:
df_obs_merged = df_obs.merge(
        df_species, 
        left_on='species', 
        right_on='french_name', 
        how='left',
        suffixes=('', '_species')
    )
#transect_habitat = df_gps.groupby('transect')['habitat'].first().reset_index()
#df_full = df_obs_merged.merge(
#     transect_habitat,
#     on='transect',
#     how='left'
#)
#Un transect peut avoir plusieurs habitats selon les points, on merge donc avec les points

# Extraire le numéro après le P
#df_gps['point'] = df_gps['point_id'].str.extract(r'P(\d+)')[0]
#missing_points = df_gps[df_gps['point'].isna()]
#print(missing_points)

df_gps['point_id'] = df_gps['point_id'].replace('SIPI', 'S1P1')

df_gps['point'] = df_gps['point_id'].str.extract(r'P(\d+)')[0].astype(int)
df_obs['point'] = df_obs['point'].astype(int)

df_full = df_obs_merged.merge(
    df_gps[['transect', 'point', 'X', 'Y', 'habitat']],
    on=['transect', 'point'],
    how='left'
)

## 2. Dataset Structure

In [48]:
# Table dimensions
print("="*60)
print("TABLE DIMENSIONS")
print("="*60)

print(f"\n1. SPECIES table:")
print(f"   - {len(df_species)} species")
print(f"   - {df_species['status'].nunique()} status categories")

print(f"\n2. GPS-MILIEU table:")
print(f"   - {len(df_gps)} observation points")
print(f"   - {df_gps['transect'].nunique()} transects")
print(f"   - {df_gps['habitat'].nunique()} habitat types")

print(f"\n3. OBSERVATIONS table:")
print(f"   - {len(df_obs):,} raw observations")
print(f"   - {len(df_full):,} enriched observations")
print(f"   - {df_full.shape[1]} columns")

============================================================
TABLE DIMENSIONS
============================================================

1. SPECIES table:
   - 87 species
   - 8 status categories

2. GPS-MILIEU table:
   - 650 observation points
   - 65 transects
   - 7 habitat types

3. OBSERVATIONS table:
   - 114,495 raw observations
   - 115,304 enriched observations
   - 32 columns

In [ ]:
#Drop si on ne sait pas ce qui a été observé
df_full = df_full.dropna(subset=['french_name', 'scientific_name'], how='all')

In [ ]:
# Remplacer les valeurs manquantes dans clouds, rain, wind, visibility (itératif avec RandomForest)

cols_to_impute = ['clouds', 'rain', 'wind', 'visibility']

for c in cols_to_impute:
    df_full[c] = pd.to_numeric(df_full[c], errors='coerce')


data_to_impute = df_full[cols_to_impute]

imputer = IterativeImputer(
    estimator=RandomForestRegressor(n_estimators=100, random_state=42),
    max_iter=10,
    random_state=42
)
df_full[cols_to_impute] = imputer.fit_transform(df_full[cols_to_impute])

print(df_full[cols_to_impute].isna().sum())

imputer = IterativeImputer(
    estimator=RandomForestRegressor(n_estimators=100, random_state=42),
    max_iter=10,
    random_state=42
)

data_imputed = imputer.fit_transform(data_to_impute)

df_full[cols_to_impute] = data_imputed

df_full

clouds        0
rain          0
wind          0
visibility    0
dtype: int64

,observer,dept_code,transect,date,visit_number,clouds,rain,wind,visibility,point,...,visual__no_flight_total,auditory_visual_no_flight_total,auditory_visual_with_flight_total,Notes,french_name,scientific_name,status,X,Y,habitat
0,BELFAN David,972.0,fond l'etang,2014-04-12,1,2.0,1.0,1.0,1.0,1,...,0.0,1,1.0,NaN,Sucrier à ventre jaune,Coereba flaveola martinicana,Autochtone,706274,1624126,Forêt humide
1,BELFAN David,972.0,fond l'etang,2014-04-12,1,2.0,1.0,1.0,1.0,1,...,1.0,1,1.0,NaN,Sporophile cici,Melanospiza bicolor ou Tiaris bicolor,Autochtone,706274,1624126,Forêt humide
2,BELFAN David,972.0,fond l'etang,2014-04-12,1,2.0,1.0,1.0,1.0,1,...,2.0,2,2.0,NaN,Colibri falle-vert,Eulampis h. holosericeus,Endémique des Petites Antilles,706274,1624126,Forêt humide
3,BELFAN David,972.0,fond l'etang,2014-04-12,1,2.0,1.0,1.0,1.0,1,...,0.0,1,1.0,NaN,Elénie siffleuse,Elaenia m. martinica,Autochtone,706274,1624126,Forêt humide
4,BELFAN David,972.0,fond l'etang,2014-04-12,1,2.0,1.0,1.0,1.0,1,...,0.0,1,1.0,NaN,Coulicou manioc,Coccyzus minor,Autochtone,706274,1624126,Forêt humide

In [ ]:
# remplacer les valeurs manquantes dans les colonnes de comptage par 0 + recalcul des totaux

auditory_cols = ['auditory_0_25m', 'auditory_25_50m', 'auditory_50_100m', 'auditory_100m_plus']
visual_cols = ['visual_0_25m', 'visual_25_50m', 'visual_50_100m', 'visual_100m_plus']
flight = ['flight']
for c in auditory_cols + visual_cols + flight:
    df_full[c] = pd.to_numeric(df_full[c], errors='coerce')
    
df_full[ auditory_cols + visual_cols + flight] = df_full[ auditory_cols + visual_cols + flight].fillna(0)

df_full.head()

totals = ['auditory_total', 'visual__no_flight_total', 'auditory_visual_no_flight_total', 'auditory_visual_with_flight_total']
for c in totals:
    df_full[c] = pd.to_numeric(df_full[c], errors='coerce')
    
df_full['auditory_total'] = df_full[auditory_cols].sum(axis=1)
df_full['visual__no_flight_total'] = df_full[visual_cols].sum(axis=1)
df_full['auditory_visual_no_flight_total'] = df_full[auditory_cols + visual_cols].sum(axis=1)
df_full['auditory_visual_with_flight_total'] = df_full[auditory_cols + visual_cols + ['flight']].sum(axis=1)

In [52]:
nan_cols = df_full.columns[df_full.isna().any()]
print(df_full[nan_cols].isna().sum())

dept_code         2
Notes        103212
status           55
dtype: int64

In [53]:
df_full.columns

Index(['observer', 'dept_code', 'transect', 'date', 'visit_number', 'clouds',
       'rain', 'wind', 'visibility', 'point', 'start_time', 'species',
       'auditory_0_25m', 'visual_0_25m', 'auditory_25_50m', 'visual_25_50m',
       'auditory_50_100m', 'visual_50_100m', 'auditory_100m_plus',
       'visual_100m_plus', 'flight', 'auditory_total',
       'visual__no_flight_total', 'auditory_visual_no_flight_total',
       'auditory_visual_with_flight_total', 'Notes', 'french_name',
       'scientific_name', 'status', 'X', 'Y', 'habitat'],
      dtype='object')

In [54]:
nan_cols = df_full.columns[df_full.isna().any()]
print(df_full[nan_cols].isna().sum())

dept_code         2
Notes        103212
status           55
dtype: int64

In [55]:
df_full['Notes'].unique()

array([nan, 'en formation  SOPHIE Stéphane/ ELY-MARIUS Séverine',
       'Compagnonnage par Beatriz Conde  ', 'Banane 100% coupé',
       "Beaucoup d'ordure et carcasse de voiture",
       'Camping de plusiers personnes sur ce site',
       'Végetation très secs', 'COMPAGNONNAGE PAR BEATRIZ CONDE',
       'CARCASSE DE VOITURE',
       'Les PRODOM ont trouvé un nouveau site de nidification la toiture du lycée',
       'Canne 100% coupé', 'Canne 70% coupé', "Aménagement d'un parking",
       'DORTOIRE', 'Canne à sucre  100% coupé', 'Canne à sucre 50% coupé',
       'FAIT PAR BEATRIZ CONDE', "Accompagner par Caroll-Ann' Portel",
       'AU NID',
       'Oiseau dans la peripherie du camps de canne- Canne a sucre basse',
       'Canne basse', 'Sans canne 50% et canne à sucre basse 50%',
       'Pas de canne', 'Bassin de traitement',
       'COMPAGNONAGE AVEC B.CONDE', "SUR L'ILET BOISSEAU",
       "Presence d'iguane", 'Compagnonnage par Beatriz CONDE',
       'COMPAGNONNAGE PAR BEATRIZ CONDE- Beaucoup de sargasses',
       'Cannes non coupées - proximité RN5', 'Cannes non coupées',
       'Cannes non coupées - emplacement du point en friche',
       'friche débroussaillée / débroussailleuse en fonctionnement',
       'canal nettoyé : reprise végétation aquatique au niveau du pont',
       'canal nettoyé', " canal envahi de jacinthe d'eau ",
       'cannes non coupées',
       'nombreuses zones de décharges sauvages entre points  5 et 6',
       'Bois Descailles : autorisation de défrichement / PC 3 lots',
       'plusieurs zones de déchets entre les points 7 et 8',
       'Décharges sauvages entre les points 8 et 9', 'cannes coupées',
       "Pont envahi de jacinthes d'eau",
       'Présence de chat / Décharge sauvage', "Jacinthes d'eau",
       "Mangouste + Jacinthes d'eau",
       "Jacinthes d'eau + végétation haute",
       'Herbes hautes : friche agricole', 'Tronçonneuse',
       'Pluie, arrêt et reprise le 20/06/2024', 'Fait par Beatriz Conde',
       'Proximité route', 'Compagnonnage par Beatriz Conde',
       "Beaucoup d'abeilles sur le gommier rouge",
       'La date de realisation du point 2 et 1 a été faite ulterieurment ',
       'sur la gauche, végétation plus haute',
       'aménagement en plus; chemin et jardin cultivé',
       "milieu plus ouvert qu'en 2023", 'végétation plus haute',
       "Travaux route/ chemin créé près d'une maison ; travaux en cours pendant le relevé",
       'Défrichement en contrebas du point/ travaux en cours',
       'Merle femelle en alerte pendant 5 min dans son nid avec ses petits ',
       'Travaux de voirie terminés/ route élargie/ végétation coupée aux abords de la route',
       '3 ouvriers présents à proximité du point',
       'BRUIT RIVIERE A PROXIMITE', 'avec Beatriz CONDE',
       'Abris pour les chats sur ce site- Compagnonnage par Beatriz Conde',
       'Maré basse le mirroir est sec', 'Ruche', 'Matinné  pluvieuse',
       'Bruit de débroussailleuse', 'Compagnonnage par B. CONDE',
       'Acompagné par Nicolas DEGRAS', "DEPOT D'ORDURES",
       'Parcelle sans banane et en labourrage de la terre',
       'Canne coupé à 100%- Compagnonnage par Beatriz Conde',
       "Compagnonnage par Beatriz Conde- Beaucoup de bruit dans l'usine",
       'Compagnonnage par Beatriz Conde- ',
       'Compagnonnage par Beatriz Conde-  BRUIT DE DEBROUSSAILLEUSE',
       'Compagnonnage par Beatriz Conde- TRACTEUR LABOURE LA TERRE',
       'Compagnonnage par Beariz Conde', 'Copagnonnage par Beatriz Conde',
       'Canne coupé à 50%', 'Oiseau en peripherie du champs de banane',
       'EN LISIER', 'Oiseau dans la peripherie du champs de canne',
       'UN TRACTEUR ATTIRZIT LES BUBIBI', 'CANNE COUPE A 100%%',
       'oiseaux en lisière longeant la rivière_ CANNE COUPE A 100%%',
       'Oiseaux en lisière de la mangrove',
       'Un arbre sur ce point qui attire les oiseaux', 'En lisier',
       "LES PRODOM SONT DANS LA TOUR DE L'USINE",
       'Compagnonnage par Beatriz CONDE- Racoune observé',
       "FIN DU DEPOT D'ORDURES", 'FIN DE DECHES SUR CE SITE',
       'TOUJOURS DES DECHETS ELETROMENAGERS- VOITURE',
       "BEAUCOUP D'ABEILLE", 'Fait par Beatriz CONDE',
       "Présece d'une voiture abndonée produisant une poluition visuel",
       "CONSTRUCTION D'UNE STATION DE CAPTAGE D'EAU", "COUPE D'ARBRES",
       'VENT TRES FORT',
       "Mise en place de deux container abri  et 3  reservoire d'eau",
       'Compagnonnage avec Beatriz CONDE',
       'Compagnonnage avec Beatriz CONDE- JECKO',
       "Nous avons fait le comptage à 100 m du point car impossible d'y accèder avce la marée haute- Compagnonnage avec Beatriz CONDE",
       'Nid BUTPLA avec adulte au nid',
       "Compagnonnage avec Beatriz CONDE- Beaucoup d'abeilles",
       'Compagnonnage Beatriz Conde', 'BRUILLARD',
       "Construction d'une maison",
       'Nouveau point 5 (précédent non atteignable)', 'Cannes coupées',
       'champs de cannes coupé',
       'mare totalement atterie + bananes et légumes',
       "Cannes coupées / pompe d'arrosage eau en fonctionnement",
       'Voisin avec musique forte', 'Déchets', 'Bruit Rivière',
       "le milieu s'est refermé, arbustes et arbres plus hauts par rapport au dernier relevé en 2019",
       'la végétation a poussé sur le fil électrique faisant face au point de relevé/ cache la visibilité face au point',
       'Accompagné de JACQUELIN Nancy',
       'Dépôts sauvages de déchets en forêts entre points 5 et 6',
       'décalage dû à la pluie',
       'Zone de déchets sauvages en ravine en arrivant sur point 8',
       'Zone de déchets sauvages en ravine entre points 8 & 9',
       'dépôt sauvage de déchets point 9',
       'Canal envahi par la végétation',
       'Chemin envahi par végétation haute',
       'Abandon du transect : végétation impénétrable => prévoir passage par canoé ou barque',
       "méandre envahi de laitue d'eau",
       'Beacoup de nuisance sonnore avec les campeurs- Compagnonnage avec Beatriz CONDE',
       "Beaucoup d'abeilles", 'JECKO', 'CORSE A PIED_ TRAK',
       'Mangouste, tortoue de floride', '2 tortues de Floride',
       '3 tortues de Floride', '4 tortues de Floride',
       '5 tortues de Floride', '6 tortues de Floride',
       '7 tortues de Floride', '8 tortues de Floride',
       '9 tortues de Floride', '10 tortues de Floride',
       'Comptage fait par Beatriz Conde', 'IGUANE', 'DANS LE NID',
       'Michel CAUPENNE et Fabienne JOHANNO de la LPO',
       'Accompagnr par Michel CAUPENNE ET Fabienne JOHANNO de la LPO',
       'Fait par la contributrice', 'Compagnonnage par Beatrize Conde',
       'Machine sur le chaps de canne à sucre', 'mygale juve',
       'EN PERIPHERIE', 'Canne à sucré coupé 50%',
       'Cana à sucré coupé 50%', 'Canne à sucré coupé 70%',
       'Rivière 20% Repousse canne 80%',
       'Mangrove 50% Repousse canne 50%',
       'REPOUSSE DES CANNE A SUCRE A 100%', "DOUGALL SUR L'ILET PELEE",
       "Presence de 3 chats- Plantes exotique dans des pots à l'entré du restaurent- pas de toillete pour le restaurent  ",
       "SUR L'ILET BOISSEAU EN VOL", "SUR L'ILET BOISSEAU ",
       "SUR L'ILET PETIT PITON EN VOL",
       "Travaux sur la route et j'ai preferé faire le tours et commencer Verrier et finir en suite Jannot",
       'PLUIE', 'Pluie fine', ' 2 JECKO',
       'Le contributeur est retourné à une autre date pour finir les deux dernier points car le portail se trouvé fermé.',
       "La pluie n'a pas permis de réaliser le relevé",
       "La pluie a gêné la réalisation du relevé - effectué de la voiture ; observation d'une mangouste",
       'PLATELAGE IMPRATICABLE DETOUR PAR LA ROUTE ENTRE LE 10 DE VATABLE 1 ET LA 1 DE VATABLE 2',
       'Acompagné par ALEXANDRINE Noham  '], dtype=object)

In [57]:
df_full.columns

Index(['observer', 'dept_code', 'transect', 'date', 'visit_number', 'clouds',
       'rain', 'wind', 'visibility', 'point', 'start_time', 'species',
       'auditory_0_25m', 'visual_0_25m', 'auditory_25_50m', 'visual_25_50m',
       'auditory_50_100m', 'visual_50_100m', 'auditory_100m_plus',
       'visual_100m_plus', 'flight', 'auditory_total',
       'visual__no_flight_total', 'auditory_visual_no_flight_total',
       'auditory_visual_with_flight_total', 'Notes', 'french_name',
       'scientific_name', 'status', 'X', 'Y', 'habitat'],
      dtype='object')